name: 'Cat for GitHub Actions'
description: 'cat command like action'
author: 'pCYSl5EDgo'
inputs:
  path:
    description: 'A file to read'
    required: true
  trim:
    description: 'Remove whitespace from both ends of a string when true. Default is false.'
    default: false
outputs:
  text:
    description: 'A file content read from path'
runs:
  using: 'node12'
  main: 'dist/main.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
