name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - feature/*
      - bugfix/*
  push:
    branches:
      - master
      - feature/*
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
#      - name: Installing the packages
#        run: |
#          echo "##[set-output name=output;]$( npm install )"
#        id: install
#      - name: run test
#        id: run_tests
#        run: |
#          echo "::set-output name=mix-test::$(npm test)\n"
      - name: install and echo
        run: |
          npm install $@ >> log.txt
          if [  ${PIPESTATUS[0]} -gt 0 ]
            then
              exit 1
            pwd
          fi
        id: echo_output_js_failure

      - name: build
        run: |
            npm run build $@ >>  log.txt
            if [  ${PIPESTATUS[0]} -gt 0 ]
              then
                exit 1
              pwd
            fi
        id: build

      - name: forming log url
        id: log_url
        run: ./__scripts__/hello-world.sh


        # unzip the tar and read it

        env:
           TEXT: ${{ steps.file_read.outputs.text }}
        if: always()
      - name: printing
        id: log_url_print
        run: |
            echo "Log URL is : ${{ steps.log_url.outputs.text }}"
        env:
            LOG_URL: ${{ steps.log_url.outputs.log_url }}
        if: always()


#https://github:com/swapneshran/realworld/commit/254d81d2b03a29791384145072b5d26548097451/checks/862475895/logs:


