name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - feature/*
      - bugfix/*
  push:
    branches:
      - master
      - feature/*
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
#      - name: Installing the packages
#        run: |
#          echo "##[set-output name=output;]$( npm install )"
#        id: install
#      - name: run test
#        id: run_tests
#        run: |
#          echo "::set-output name=mix-test::$(npm test)\n"
      - name: install and echo
        run: |
          npm install $@ | tee log.txt
          if [  ${PIPESTATUS[0]} -gt 0 ]
            then
              exit 1
            pwd
          fi
        id: echo_output_js_failure

      - name: build
        run: |
            npm run build $@ | tee log.txt
            if [  ${PIPESTATUS[0]} -gt 0 ]
              then
                exit 1
              pwd
            fi
        id: build

  publish_to_teams:
      runs-on: ubuntu-latest
      continue-on-error: true
      uses: ./
      name: show_out put
      id: file_read
      with:
        path: log.txt
    - run: |
        echo $TEXT
        curl google.com
      env:
        TEXT: ${{ steps.file_read.outputs.text }}
