name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - feature/*
      - bugfix/*
  push:
    branches:
      - master
      - feature/*
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    outputs:
      output1: ${{ steps.install.outputs.install }}
      output2: ${{ steps.test.outputs.test }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - id: install
        run: |
          npm install
        #run: echo "::set-output name=test::hello"
#      - run: npm run build

      - name: run test
        id: run_tests
        run: |
          echo "::set-output name=mix-test::$(npm test)\n"
      - id: echo_output_js_failure
        run: echo "${{join(steps.run_tests.outputs.*, '\n')}} "
        #run: echo "::set-output name=test::world"
#      - id: step_output
#        run: __scripts__/hello-world.sh
      #- run: npm test
#  send_to_teams:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - run: echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}}
      #- run: __scripts__/hello-world.sh  ${{needs.build.outputs.output1}}
