name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - feature/*
      - bugfix/*
  push:
    branches:
      - master
      - feature/*
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
#      - name: Installing the packages
#        run: |
#          echo "##[set-output name=output;]$( npm install )"
#        id: install
#      - name: run test
#        id: run_tests
#        run: |
#          echo "::set-output name=mix-test::$(npm test)\n"
      - name: install and echo
        run: |
          npm install $@ |&  tee -a log.txt
          if [  ${PIPESTATUS[0]} -gt 0 ]
            then
              exit 1
            pwd
          fi
        id: echo_output_js_failure

      - name: build
        run: |
            npm run build $@ |&  tee -a log.txt
            if [  ${PIPESTATUS[0]} -gt 0 ]
              then
                exit 1
              pwd
            fi
        id: build
      - uses: ./
        name: show_out put
        id: file_read
        with:
          path: log.txt
        if: always()
      - run: |
          echo "$GITHUB_RUN_ID"
          echo "$GITHUB_TOKEN"
          echo $TEXT
          SHA_ID = $(curl -X  GET \
            https://api.github.com/repos/swapneshran/realworld/actions/runs \
            -H 'Authorization: tokenw ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
           | jq '.workflow_runs[0].head_sha)'
          echo "$SHA_ID"
        env:
           TEXT: ${{ steps.file_read.outputs.text }}
        if: always()





