name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - feature/*
      - bugfix/*
  push:
    branches:
      - master
      - feature/*
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  install:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: forming log url
        id: log_url
        run: |
          echo "getting Log URL"
          echo "ACTION_ID: $GITHUB_ACTION"
          echo "$GITHUB_TOKEN"


          echo "getting Log URL"
          SHA_ID=$(curl -X  GET \
                            https://api.github.com/repos/swapneshran/realworld/actions/runs \
                            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
                            -H "Accept: application/vnd.github.v3+json" \
                            | jq -r --arg GITHUB_RUN_ID "GITHUB_RUN_ID"  -c '.workflow_runs[] | select( .id | contains('$GITHUB_RUN_ID')) | .head_sha'  \
                            | sed 's/"//g')
          SHA_ID2=$(curl -X  GET \
                             https://api.github.com/repos/swapneshran/realworld/commits/$SHA_ID/check-runs\
                             -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
                             -H "Accept: application/vnd.github.antiope-preview+json" \
                              | jq '.check_runs[0].id')

          LOG_URL=("https://github.com/swapneshran/realworld/commit/$SHA_ID/checks/$SHA_ID2/logs")
          echo $LOG_URL
          echo "Check suite id is $SHA_ID2"
          LOG_URL=("https://github.com/swapneshran/realworld/commit/$SHA_ID/checks/$SHA_ID2/logs")
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\// /g')
           echo "Branch name $BRANCH_NAME"
          echo "##[set-output name=log_url;]$LOG_URL"
          echo "##[set-output name=branch;]$GITHUB_REF"

        env:
          TEXT: ${{ steps.file_read.outputs.text }}
      - name: install and echo
        run: |
          npm install
        id: echo_output_js_failure
      #      - name: build
      #        run: |
      #            npm run build
      #
      #        id: build
      #        if: always()
      - name: printing
        id: log_url_print
        run: |
          echo "Log URL is : $LOG_URL"
          echo "branch name is $BRANCH_NAME"
        env:
          LOG_URL: ${{ steps.log_url.outputs.log_url }}
          BRANCH_NAME: ${{ steps.log_url.outputs.branch }}
        if: always()


  build:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: echo hello world
        id: echo_hello_world
        run: |
          echo "Hello World"
      - name: run npm build
        id: npm_buold
        run: |
            npm build
  lint:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: running the linte
        id: run_lint
        run: |
            exit(1)
#https://github:com/swapneshran/realworld/commit/254d81d2b03a29791384145072b5d26548097451/checks/862475895/logs:


